'use strict';

const crypto = require('crypto');

const { buildCart }               = require('./cartService');
const { negotiate, applyOffer }   = require('./negotiationService');
const { validateUserPolicy,
        validateMerchantPolicy }  = require('./policyService');
const { parseIntent }             = require('./intentService');
const { appendAudit, createAudit } = require('./auditService');
const catalog                     = require('./data/catalog.json');

// ─── helpers ──────────────────────────────────────────────────────────────────

/**
 * After a negotiation, derive the best available cart.
 * - approved  → use finalCart (already fully resolved)
 * - escalated → re-apply all valid offers from the round history to get
 *               as far as the merchant managed to reduce
 *
 * @param {{ items:Array, total:number, budget:number }} originalCart
 * @param {object} negotiationResult
 */
function getEffectiveCart(originalCart, negotiationResult) {
  if (negotiationResult.status === 'approved') {
    return negotiationResult.finalCart;
  }
  // Re-apply every successful offer from the escalation trace
  let cart = originalCart;
  for (const { offer } of negotiationResult.offers ?? []) {
    if (offer.action === 'substitute' && offer.replacement) {
      cart = applyOffer(cart, offer);
    }
  }
  return cart;
}

/**
 * Decide the final transaction outcome.
 *
 * Priority (highest to lowest):
 *   1. escalated — negotiation failed OR merchant policy escalated
 *   2. rejected  — any policy returned rejected
 *   3. approved  — everything passed
 *
 * @param {object} negotiationResult
 * @param {PolicyResult} userPolicyResult
 * @param {PolicyResult} merchantPolicyResult
 * @returns {{ decision: string, reasoning: string }}
 */
function decide(negotiationResult, userPolicyResult, merchantPolicyResult) {
  if (negotiationResult.status === 'escalation_needed') {
    return {
      decision:  'escalated',
      reasoning: `Escalated. Negotiation could not close the budget gap of ₹${negotiationResult.gap} within ${negotiationResult.rounds} round(s). Requires manual review.`,
    };
  }

  if (merchantPolicyResult.status === 'escalated') {
    return {
      decision:  'escalated',
      reasoning: `Merchant policy requires escalation: ${merchantPolicyResult.reason}`,
    };
  }

  if (userPolicyResult.status === 'rejected') {
    return {
      decision:  'rejected',
      reasoning: `User policy rejected: ${userPolicyResult.reason}`,
    };
  }

  if (merchantPolicyResult.status === 'rejected') {
    return {
      decision:  'rejected',
      reasoning: `Merchant policy rejected: ${merchantPolicyResult.reason}`,
    };
  }

  return {
    decision:  'approved',
    reasoning: `Negotiation succeeded in ${negotiationResult.rounds} round(s). All policies approved.`,
  };
}

/**
 * Run the full purchase pipeline given a parsed intent.
 * Pure function — no LLM calls here. Accepts intent directly so it is
 * independently testable without a network.
 *
 * An optional transactionId may be passed in (generated by the route handler
 * after intent parsing). When provided, AuditEntries are appended after each
 * step. When omitted (unit tests without audit context), appendAudit is a
 * graceful no-op.
 *
 * Pipeline:
 *   buildCart → negotiate → validateUserPolicy → validateMerchantPolicy → decide
 *
 * @param {Intent}   intent
 * @param {CatalogProduct[]} cat
 * @param {{ max_spending: number, allowed_categories: string[] }} userPolicy
 * @param {{ max_discount: number, min_margin: number }} merchantPolicy
 * @param {string} [transactionId]   — optional; generated internally if omitted
 * @returns {{ transactionId, decision, reasoning, fullTrace }}
 */
function orchestrate(intent, cat, userPolicy, merchantPolicy, transactionId) {
  const txId = transactionId ?? crypto.randomUUID();

  // 1. Build initial (un-budgeted) cart
  const cart = buildCart(intent, cat);
  appendAudit(txId, { step: 'cart_building', input: { intent }, output: cart });

  // 2. Negotiate (up to 2 rounds)
  const negotiationResult = negotiate(cart, intent, cat);
  appendAudit(txId, { step: 'negotiation', input: { cart, intent }, output: negotiationResult });

  // 3. Derive the best available cart after negotiation
  const effectiveCart = getEffectiveCart(cart, negotiationResult);

  // 4. Policy gates
  const userPolicyResult = validateUserPolicy(effectiveCart, userPolicy);
  appendAudit(txId, { step: 'user_policy_validation', input: { cart: effectiveCart, userPolicy }, output: userPolicyResult });

  const merchantPolicyResult = validateMerchantPolicy(
    negotiationResult.best_offer ??
    negotiationResult.offers?.[negotiationResult.offers.length - 1]?.offer ??
    { action: 'no_offer', replacement: null, saving: 0, reason: 'no offer made' },
    merchantPolicy
  );
  appendAudit(txId, { step: 'merchant_policy_validation', input: { offer: negotiationResult.best_offer, merchantPolicy }, output: merchantPolicyResult });

  // 5. Decision
  const { decision, reasoning } = decide(
    negotiationResult, userPolicyResult, merchantPolicyResult
  );
  appendAudit(txId, { step: 'decision', input: { negotiationResult, userPolicyResult, merchantPolicyResult }, output: { decision, reasoning } });

  // 6. Assemble response (structured, not serialised to string)
  const fullTrace = {
    intent,
    cart,
    negotiation:         negotiationResult,
    userPolicyResult,
    merchantPolicyResult,
    decision,
  };

  return {
    transactionId: txId,
    decision,
    reasoning,
    fullTrace,
  };
}

// ─── Express route handler ────────────────────────────────────────────────────

/**
 * POST /api/purchase
 *
 * Body:
 *   {
 *     userText:       string,
 *     userPolicy:     { max_spending, allowed_categories },
 *     merchantPolicy: { max_discount, min_margin }
 *   }
 */
async function purchaseHandler(req, res) {
  const { userText, userPolicy, merchantPolicy } = req.body ?? {};

  if (!userText) {
    return res.status(400).json({ error: 'userText is required' });
  }
  if (!userPolicy || !merchantPolicy) {
    return res.status(400).json({ error: 'userPolicy and merchantPolicy are required' });
  }

  try {
    const txId = crypto.randomUUID();
    createAudit(txId);

    const intent = await parseIntent(userText);
    appendAudit(txId, { step: 'intent_parsing', input: { userText }, output: intent });

    const result = orchestrate(intent, catalog, userPolicy, merchantPolicy, txId);
    return res.json(result);
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
}

module.exports = { orchestrate, purchaseHandler };
